ruta: jdbc:mysql://dam2.mysql.iesquevedo.es:3335/JosephEscribano_Encriptacion?ServerTimeZone=GMT+2&useSSL=false
user: root
password: quevedo2dam
driver: com.mysql.cj.jdbc.Driver
passKeyStore: servidor